name: News Scraper
on:
  schedule:
    - cron: "*/10 * * * *" # Runs every 10 minutes
  workflow_dispatch: # Allows you to click a button to run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Run Scraper
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          OPENMODEL_API: ${{ secrets.OPENMODEL_API }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
        run: go run main.go
