name: News Scraper

on:
  repository_dispatch:
    types: [run-scraper]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26"
      - name: Run Scraper
        env:
          TELEGRAM_BOT_TOKEN: ${{ vars.TELEGRAM_BOT_TOKEN }}
          GEMINI_API: ${{ vars.GEMINI_API }}
          REDIS_URL: ${{ vars.REDIS_URL }}
        run: |
          go mod tidy
          go run cmd/api/main.go
